name: CI - BackEnd

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: |
          dotnet tool restore
          dotnet restore ./DesafioTjRjErlimar.sln
        working-directory: ./backend

      - name: Build -c Debug
        run: |
          dotnet build ./DesafioTjRjErlimar.sln --nologo -c Debug --no-restore --no-incremental -warnaserror
        working-directory: ./backend

      - name: Build -c Release
        run: |
          dotnet build ./DesafioTjRjErlimar.sln --nologo -c Release --no-restore --no-incremental -warnaserror
        working-directory: ./backend

      - name: Test -c Debug
        run: |
          dotnet test ./DesafioTjRjErlimar.sln --nologo -c Debug --no-build --verbosity normal
        working-directory: ./backend

      - name: Test -c Release
        run: |
          dotnet test ./DesafioTjRjErlimar.sln --nologo -c Release --no-build --verbosity normal
        working-directory: ./backend